export const API = 'http://34.125.237.140/api'

export const ADMIN = 'traumqq@gmail.com'

export const ACTIONS = {
	GET_PRODUCTS: 'GET_PRODUCTS',
	GET_ONE_PRODUCT: 'GET_ONE_PRODUCT',
	GET_GENRE: 'GET_GENRE',
	ADD_COMMENT: 'ADD_COMMENT',
	GET_COMMENTS: 'GET_COMMENTS',
	CHECK_COMMENT: 'CHECK_COMMENT',
	DELETE_COMMENT: 'DELETE_COMMENT',
	LIKE_COMMENT: 'LIKE_COMMENT',
	GET_FAVORITES: 'GET_FAVORITES',
	ADD_FAVORITE: 'ADD_FAVORITE',
	CHECK_FAVORITE: 'CHECK_FAVORITE',
	DELETE_FAVORITE: 'DELETE_FAVORITE',
	GET_VIEWED: 'GET_VIEWED',
	ADD_VIEWED: 'ADD_VIEWED',
	CHECK_VIEWED: 'CHECK_VIEWED',
	DELETE_VIEWED: 'DELETE_VIEWED',
}
