export const API = "http://34.125.237.140/api";
export const ADMIN = "";

export const ACTIONS = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_ONE_PRODUCT: "GET_ONE_PRODUCT",
  GET_CATEGORIES: "GET_CATEGORIES",
  ADD_COMMENT: "ADD_COMMENT",
  GET_COMMENTS: "GET_COMMENTS",
  CHECK_COMMENT: "CHECK_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
};
